django_samples/django_bookmarks/src/django_bookmarks/urls.py
import os
from bookmarks.views import *
from bookmarks.feeds import *
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

site_media = os.path.join(
	os.path.dirname(__file__), 'site_media'
)

# Create the feeds dict before the url pattern
feeds = {
	'recent': RecentBookmarks,
	'user': UserBookmarks
}

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^django_bookmarks/', include('django_bookmarks.foo.urls')),
    # Browsing
    (r'^$', main_page),
    (r'^user/(\w+)/$', user_page),
    
    # Session management
    (r'^login/$', 'django.contrib.auth.views.login'),
    (r'^logout/$', logout_page),
    (r'^register/$', register_page),
    (r'^register/success/$', direct_to_template, {'template': 'registration/register_success.html'}),
    (r'^password/$', 'django.contrib.auth.views.password_change'),
    (r'^password/success$', 'django.contrib.auth.views.password_change_done'),
    
    # Bookmark management
    (r'^save/$', bookmark_save_page),
    (r'^tag/$', tag_cloud_page),
    (r'^tag/([^\s]+)/$', tag_page),
    (r'^search/$', search_page),
    (r'^ajax/tag/autocomplete/$', ajax_tag_autocomplete),
    (r'^vote/$', bookmark_vote_page),
    (r'^popular/$', popular_bookmark_page),
    (r'^bookmark/(\d+)/$', bookmark_page),
    
    # Friends
    (r'^friends/(\w+)/$', friends_page),
    (r'^friend/add/$', friend_add),
    (r'^friend/invite/$', friend_invite),
    (r'^friend/accept/(\w+)/$', friend_accept),
    
    # Comments
    (r'^comments/', include('django.contrib.comments.urls')),
    
    # Feeds
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
    
    # i18n
    (r'^i18n/', include('django.conf.urls.i18n')),
    
    # Static files
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': site_media}),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    (r'^admin/', include(admin.site.urls)),
)

django_samples/django_bookmarks/src/django_bookmarks/bookmarks/models.py
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.template.loader import get_template
from django.template import Context
from django.conf import settings
from django.db import models

class Link(models.Model):
	url = models.URLField(unique=True)
	
	def __unicode__(self):
		return self.url

class Bookmark(models.Model):
	title = models.CharField(max_length=200)
	user = models.ForeignKey(User)
	link = models.ForeignKey(Link)
	
	def __unicode__(self):
		return u'%s, %s' % (self.user.username, self.link.url)
	
	def get_absolute_url(self):
		return self.link.url

class Tag(models.Model):
	name = models.CharField(max_length=64, unique=True)
	bookmarks = models.ManyToManyField(Bookmark)
	
	def __unicode__(self):
		return self.name

class SharedBookmark(models.Model):
	bookmark = models.ForeignKey(Bookmark, unique=True)
	date = models.DateTimeField(auto_now_add=True)
	votes = models.PositiveIntegerField(default=1)
	users_voted = models.ManyToManyField(User)
	
	def __unicode__(self):
		return u'%s, %s' % (self.bookmark, self.votes)

class Friendship(models.Model):
	from_friend = models.ForeignKey(
		User,
		related_name = 'friend_set'
	)
	to_friend = models.ForeignKey(
		User,
		related_name = 'to_friend_set'
	)
	
	def __unicode__(self):
		return u'%s, %s' % (
			self.from_friend.username,
			self.to_friend.username
		)
	
	class Meta:
		unique_together = (('from_friend', 'to_friend'), )

class Invitation(models.Model):
	name = models.CharField(max_length=50)
	email = models.EmailField()
	code = models.CharField(max_length=20)
	sender = models.ForeignKey(User)
	
	def __unicode__(self):
		return u'%s, %s' % (self.sender.username, self.email)
	
	def send(self):
		subject = u'Invitation to join Django Bookmarks'
		link = 'http://%s/friend/accept/%s/' % (
			settings.SITE_HOST,
			self.code
		)
		template = get_template('invitation_email.txt')
		context = Context({
			'name': self.name,
			'link': link,
			'sender': self.sender.username,
		})
		message = template.render(context)
		send_mail(
			subject,
			message,
			settings.DEFAULT_FROM_EMAIL,
			[self.email]
		)

django_samples/django_bookmarks/src/django_bookmarks/templates/base.html
{% load i18n %}

<!doctype html>  
<html lang="en">
<head>
  <meta charset="utf-8" />
  <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>Django Bookmarks | {% block title %}{% endblock %}</title>
  <meta name="description" content="bookmarks application" />
  <meta name="viewport" content="width=device-width; initial-scale=1.0" />
  <link rel="stylesheet" href="/site_media/style.css" />
  <script src="/site_media/jquery-1.4.2.min.js"></script>
  {% block external %}{% endblock %}
</head>

<body>
  <div>
    <nav><div id="nav">
      {% if user.is_authenticated %}
        {{ user.username }}:
      {% endif %}
      <a href="/">home</a> |
      <a href="/popular">popular</a> |
      {% if user.is_authenticated %}
        <a href="/search/">search</a> |
        <a href="/user/{{ user.username }}/">my bookmarks</a> |
        <a href="/save/">new bookmark</a> |
        <a href="/password/">password</a> |
        <a href="/logout">logout</a>
      {% else %}
        <a href="/login/">login</a> |
        <a href="/register/">register</a>
      {% endif %}
    </div></nav>
    <header>
      <h1>{% block head %}{% endblock %}</h1>
    </header>
    {% if messages %}
    	<ul class="messages">
    			{% for message in messages %}
    				<li>{{ message }}</li>
    			{% endfor %}
    	</ul>
    {% endif %}
    <div>
      {% block content %}{% endblock %}
    </div>
    
    <footer>
    	<div id="footer">
    		<form action="/i18n/setlang/" method="post">
    			{% csrf_token %}
    			<select name="language">
    				{% for lang in LANGUAGES %}
    				<option value="{{ lang.0 }}">{{ lang.1 }}</option>
    				{% endfor %}
    			</select>
    			<input type="submit" value="Go" />
    		</form>
    	</div>
    	{% block footer %}
      <small>Marc-Aur&egrave;le Brothier - 2010</small>
      {% endblock %}
    </footer>
  </div>
</body>
</html>

django_samples/django_bookmarks/src/django_bookmarks/templates/bookmark_list.html
{% if bookmarks %}
<ul class="bookmarks">
  {% for bookmark in bookmarks %}
    <li><a href="{{ bookmark.link.url }}" class="title">{{ bookmark.title }}</a>
      {% if show_edit %}
        <a href="/save/?url={{ bookmark.link.url|urlencode }}" class="edit">[edit]</a>
      {% endif %}
      <br/>
      {% if show_tags %}
        Tags:
        {% if bookmark.tag_set.all %}
          <ul class="tags">
          {% for tag in bookmark.tag_set.all %}
            <li><a href="/tag/{{ tag.name|urlencode }}/">{{ tag.name }}</a></li>
          {% endfor %}
          </ul>
        {% else %}
          None.
        {% endif %}
        <br/>
      {% endif %}
      
      {% if show_user %}
        Posted by:
        <a href="/user/{{ bookmark.user.username }}/" class="username">{{ bookmark.user.username }}</a>
      {% endif %}
    </li>
  {% endfor %}
</ul>
{% if show_paginator %}
	<div class="paginator">
		{% if has_prev %}
			<a href="?page={{ prev_page }}">&laquo; Previous</a>
		{% endif %}
		{% if has_next %}
			<a href="?page={{ next_page }}">Next &raquo;</a>
		{% endif %}
		(Page {{ page }} of {{ pages }})
	</div>
{% endif %}
{% else %}
<p>No bookmarks found.</p>
{% endif %}

django_samples/django_bookmarks/src/django_bookmarks/templates/bookmark_page.html
{% extends "base.html" %}
{% load comments %}

{% block title %}Bookmark: {{ shared_bookmark.bookmark.title }}{% endblock %}

{% block head %}
	<a href="/vote/?id={{ shared_bookmark.id }}" class="vote">[+]</a>
  <a href="{{ shared_bookmark.bookmark.link.url }}" class="title">{{ shared_bookmark.bookmark.title }}</a>
{% endblock %}

{% block content %}
  Posted by:
  <a href="/user/{{ shared_bookmark.bookmark.user.username }}/" class="username">{{ shared_bookmark.bookmark.user.username }}</a>
  |
  <span class="vote-count">Votes: {{ shared_bookmark.votes }}</span>
  
  <h2>Comments</h2>
  {% get_comment_count for bookmarks.sharedbookmark shared_bookmark.id as comment_count %}
  {% get_comment_list for bookmarks.sharedbookmark shared_bookmark.id as comment_list %}
  
  {% for comment in comment_list %}
  <div class="comment">
  	<p><em>{{ comment.user.username }}</em> said:</p>
  	{{ comment.comment|escape|urlizetrunc:40|linebreaks }}
  </div>
  {% endfor %}
  <p>Number of comments: {{ comment_count }}</p>
  
  {% render_comment_form for bookmarks.sharedbookmark shared_bookmark.id %}
{% endblock %}

django_samples/django_bookmarks/src/django_bookmarks/templates/bookmark_save.html
{% extends "base.html" %}

{% block external %}
	<script src="/site_media/jquery-ui-1.8.5.custom.min.js"></script>
	<script src="/site_media/tag_autocomplete.js"></script>
{% endblock %}

{% block title %}Save Bookmark{% endblock %}

{% block head %}Save Bookmark{% endblock %}

{% block content %}
  {% include "bookmark_save_form.html" %}
{% endblock %}

django_samples/django_bookmarks/src/django_bookmarks/templates/bookmark_save_form.html
  <form id="save-form" method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save" />
  </form>

django_samples/django_bookmarks/src/django_bookmarks/templates/friend_invite.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Invite a friend' %}{% endblock %}

{% block head %}{% trans 'Invite a friend' %}{% endblock %}

{% block content %}
	{% trans 'Enter your friend name and email below, and click "send invite" to invite your friend to join the site:' %}
	<form method="post" action=".">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="{% trans 'send invite' %}" />
	</form>
{% endblock %}

django_samples/django_bookmarks/src/django_bookmarks/templates/friends_page.html
{% extends "base.html" %}

{% block title %}Friends for {{ username }}{% endblock %}

{% block head %}Friends for {{ username }}{% endblock %}

{% block content %}
  <h2>Friends list</h2>
  {% if friends %}
  	<ul class="friends">
  		{% for friend in friends %}
  			<li><a href="/user/{{ friend.username }}/">{{ friend.username }}</a></li>
  		{% endfor %}
  	</ul>
  {% else %}
  <p>No friends found.</p>
  {% endif %}
  <a href="/friend/invite/">Invite a friend!</a>
  <h2>Latest Friend Bookmarks</h2>
  {% include "bookmark_list.html" %}
{% endblock %}

django_samples/django_bookmarks/src/django_bookmarks/templates/main_page.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block head %}Welcome to Django Bookmarks{% endblock %}

{% block external %}
	<link rel="alternate" type="application/rss+xml" title="Django Bookmarks | Recent Bookmarks" href="/feed/recent/">
{% endblock %}

{% block content %}
  {% if user.username %}
  <p>Welcome {{ user.username }}! Here you can store and share bookmarks!</p>
  {% else %}
  <p>Welcome anonymous user! You need to <a href="/login/">login</a> before
  you can store and share bookmarks.</p>
  {% endif %}
  <h2>Shared Bookmarks</h2>
  {% include "shared_bookmark_list.html" %}
{% endblock %}

django_samples/django_bookmarks/src/django_bookmarks/templates/popular_tag.html
{% extends "base.html" %}

{% block title %}Popular Bookmarks{% endblock %}

{% block head %}Popular Bookmarks{% endblock %}

{% block content %}
  {% include "shared_bookmark_list.html" %}
{% endblock %}

django_samples/django_bookmarks/src/django_bookmarks/templates/search.html
{% extends "base.html" %}

{% block external %}
<script src="/site_media/search.js"></script>
{% endblock %}

{% block title %}Search Bookmarks{% endblock %}

{% block head %}Search Bookmarks{% endblock %}

{% block content %}
  <form id="search-form" method="get" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="search" />
  </form>
  <div id="search-results">
    {% if show_results %}
      {% include "bookmark_list.html" %}
    {% endif %}
  </div>
{% endblock %}

django_samples/django_bookmarks/src/django_bookmarks/templates/shared_bookmark_list.html
{% if shared_bookmarks %}
<ul class="bookmarks">
  {% for shared_bookmark in shared_bookmarks %}
    <li>
    	<a href="/vote/?id={{ shared_bookmark.id }}" class="vote">[+]</a>
    	<a href="{{ shared_bookmark.bookmark.link.url }}" class="title">{{ shared_bookmark.bookmark.title }}</a>
      <br/>
      Posted by:
      <a href="/user/{{ shared_bookmark.bookmark.user.username }}/" class="username">{{ shared_bookmark.bookmark.user.username }}</a>
      |
      <span class="vote-count">Votes: {{ shared_bookmark.votes }}</span>
      |
      <a href="/bookmark/{{ shared_bookmark.id }}/">Comments</a>
    </li>
  {% endfor %}
</ul>
{% else %}
<p>No bookmarks found.</p>
{% endif %}

django_samples/django_bookmarks/src/django_bookmarks/templates/tag_cloud_page.html
{% extends "base.html" %}

{% block title %}Tag Cloud{% endblock %}

{% block head %}Tag Cloud{% endblock %}

{% block content %}
  <div id="tag-cloud">
    {% for tag in tags %}
      <a href="/tag/{{ tag.name|urlencode }}/" class="tag-cloud-{{ tag.weight }}">
        {{ tag.name }}
      </a>
    {% endfor %}
  </div>
{% endblock %}

django_samples/django_bookmarks/src/django_bookmarks/templates/tag_page.html
{% extends "base.html" %}

{% block title %}Tag: {{ tag_name }}{% endblock %}

{% block head %}Bookmarks for tag: {{ tag_name }}{% endblock %}

{% block content %}
  {% include "bookmark_list.html" %}
{% endblock %}

django_samples/django_bookmarks/src/django_bookmarks/templates/user_page.html
{% extends "base.html" %}

{% block external %}
  <script src="/site_media/bookmark_edit.js"></script>
  <link rel="alternate" type="application/rss+xml" title="Django Bookmarks | Bookmarks for {{ username }}" href="/feed/user/{{ user.username }}/">
{% endblock %}

{% block title %}{{ username }}{% endblock %}

{% block head %}Bookmarks for {{ username }}{% endblock %}

{% block content %}
	{% ifequal user.username username %}
		<a href="/friends/{{ username }}/">view your friends</a>
	{% else %}
		{% if is_friend %}
			<a href="/friends/{{ user.username }}/">{{ username }} is a friend of yours</a>
		{% else %}
			<a href="/friend/add/?username={{ username }}">add {{ username }} to your friends</a>
		{% endif %}
		-
		<a href="/friends/{{ username }}/">view {{ username }}'s friends</a>
	{% endifequal %}

  {% include "bookmark_list.html" %}
{% endblock %}